### PR TITLE
Pull in VG's new IO system and revise build to maybe work under vg

### PR DESCRIPTION
**Pull request by adamnovak**
I've pulled in the vgteam/vg re-implementation of stream.hpp for the new type-tagged formats, as well as everything that vg uses to deal with IO, more or less.

This necessitated adding a dependency on htslib, via pkg-config, because the VG IO is all supposed to be BGZF.

I've also trashed the CMakeLists.txt. vg needs it to build both static and dynamic versions of the library, which is fine. Except I had a lot of trouble trying to set up the CMake interface properties for the static and dynamic output targets, because I need to find both static and dynamic versions of dependencies, because when vg links against libvgio it is goiung to need to pick up from libvgio that it needs to link against -lprotobuf` and `-lhtslib` and `-ldeflate` (if your HTSlib was built with it) and so on.

I *think* I got that working, although I had to find Protobuf both the normal way and through pkg-config, because I couldn't get `find_package(Protobuf)` to run twice in the same CMakeLists.txt with different `Protobuf_USE_STATIC_LIBS` settings.

This can probably merge, if @alancleary can clean up my terrible CMake a bit with his better CMake knowledge.

But the next thing that needs to be done in order to add this as a dependency in the vg build is to have some way to communicate transitive dependencies to vg's non-CMake Makefile. We *could* just leave vg in charge of making sure it has its linking flags right itself, because it's going to be building libvgio as a submodule. But we *should* generate a pkg-config file for libvgio that contains both the dynamic and static linking options. However, I couldn't find a good way to translate what CMake knows about how to depend on the libvgio library (including a mix of lib directories, library flags, full library paths, include directories for dependencies obtained from a different prefix, etc.) into pkg-config's .pc format.

Maybe I'm overthinking this, and we just need to assume that everything we depend on is installed in the same prefix as us.

### CODE REVIEW

**Comment by alancleary** [comment]
This is quite the pull request! I'll see what I can do with the CMake file. Will hopefully have it merged some time next week.

Also, I agree that figuring out transitive dependencies would be great!

**Comment by adamnovak** [comment]
The other thing I just thought of was that maybe we can get away with
only doing the static or only the shared library build, based on a
cmake define you pass on the command line. Then vg can ask for the
static library and statically link against it, but other users can
build and link against the shared library. That would simplify the
cmake file, since we could ask for static or shared versions of
dependencies as appropriate.

The only trouble then would be getting both installed, if you decided
you actually did want to install the library on the system.

**Comment by alancleary** [comment]
That seems reasonable. Perhaps the dynamic library should be built by default if static or dynamic isn't specified since that's what people explicitly installing the library would probably want.

I think having both installed shouldn't be an issue on Unix style systems since static and dynamic libraries have different extensions and, at least in CMake, you can specify whether you want to link against a static or dynamic version of a library.

**Comment by adamnovak** [comment]
The trick would be combining the cmake config files (or pkg-config
config files, if we add that) from the static and dynamic
installations, so you can select the one you want in dependent
projects, and the later one doesn't just clobber the earlier one. But
the actual libraries would be fine to install side by side.

**Pull request merged**
